development:
  adapter: postgresql
  encoding: unicode
  database: writing-contest-database
  pool: 2
  username: mphmacbookpro
  password: news1411
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>